-- AlterTable
ALTER TABLE "Stats" ALTER COLUMN "year" SET DEFAULT DATE_PART('year', CURRENT_DATE),
ALTER COLUMN "birdies" SET DEFAULT 0,
ALTER COLUMN "snowmen" SET DEFAULT 0,
ALTER COLUMN "roundsPlayed" SET DEFAULT 0;
